name = "Myblog-Theme"
license = "MIT"
licenselink = "https://github.com/maysara-elshewehy/myblog-theme/blob/main/LICENSE"
description = "Minimal Hugo blog theme with dark mode only"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/maysara-elshewehy/myblog-theme/"

tags = ["maysara", "blog"]

min_version = "0.87.0"

# If the theme has a single author
[author]
    name = "maysara-elshewehy"
    homepage = "https://github.com/maysara-elshewehy"
